# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
Prize.create(:code => 111 , :leve => 1)
Prize.create(:code => 112 , :leve => 1)
Prize.create(:code => 113 , :leve => 1)
Prize.create(:code => 114 , :leve => 1)
Prize.create(:code => 115 , :leve => 1)
Prize.create(:code => 116 , :leve => 1)
Prize.create(:code => 558 , :leve => 2)
Prize.create(:code => 559 , :leve => 2)
Prize.create(:code => 560 , :leve => 2)
Prize.create(:code => 561 , :leve => 2)
Prize.create(:code => 562 , :leve => 2)
Prize.create(:code => 563 , :leve => 2)
Prize.create(:code => 564 , :leve => 2)
Prize.create(:code => 565 , :leve => 2)
Prize.create(:code => 566 , :leve => 2)
Prize.create(:code => 567 , :leve => 2)
Prize.create(:code => 568 , :leve => 2)
Prize.create(:code => 569 , :leve => 2)
Prize.create(:code => 570 , :leve => 2)
Prize.create(:code => 571 , :leve => 2)
Prize.create(:code => 572 , :leve => 2)
Prize.create(:code => 573 , :leve => 2)
Prize.create(:code => 574 , :leve => 2)
Prize.create(:code => 575 , :leve => 2)
Prize.create(:code => 576 , :leve => 2)
Prize.create(:code => 577 , :leve => 2)
Prize.create(:code => 866 , :leve => 3)
Prize.create(:code => 867 , :leve => 3)
Prize.create(:code => 868 , :leve => 3)
Prize.create(:code => 869 , :leve => 3)
Prize.create(:code => 870 , :leve => 3)
Prize.create(:code => 871 , :leve => 3)
Prize.create(:code => 872 , :leve => 3)
Prize.create(:code => 873 , :leve => 3)
Prize.create(:code => 874 , :leve => 3)
Prize.create(:code => 875 , :leve => 3)
Prize.create(:code => 876 , :leve => 3)
Prize.create(:code => 877 , :leve => 3)
Prize.create(:code => 878 , :leve => 3)
Prize.create(:code => 879 , :leve => 3)
Prize.create(:code => 880 , :leve => 3)
Prize.create(:code => 881 , :leve => 3)
Prize.create(:code => 882 , :leve => 3)
Prize.create(:code => 883 , :leve => 3)
Prize.create(:code => 884 , :leve => 3)
Prize.create(:code => 885 , :leve => 3)
Prize.create(:code => 886 , :leve => 3)
Prize.create(:code => 887 , :leve => 3)
Prize.create(:code => 888 , :leve => 3)
Prize.create(:code => 889 , :leve => 3)
Prize.create(:code => 890 , :leve => 3)
Prize.create(:code => 891 , :leve => 3)
Prize.create(:code => 892 , :leve => 3)
Prize.create(:code => 893 , :leve => 3)
Prize.create(:code => 894 , :leve => 3)
Prize.create(:code => 895 , :leve => 3)


